Add more options for instance types.

diff --git a/ec2-spawn-kuminami/ec2-spawn-kuminami b/ec2-spawn-kuminami/ec2-spawn-kuminami
--- a/ec2-spawn-kuminami/ec2-spawn-kuminami
+++ b/ec2-spawn-kuminami/ec2-spawn-kuminami
@@ -27,15 +27,15 @@ HOSTNAME=$2
 TYPE=$3
 
 case $TYPE in
-small)
-	AMI=$EC2_AMI_32BIT
-	;;
-large)
-	AMI=$EC2_AMI_64BIT
-	;;
+t1.micro,m1.small,c1.medium)
+        AMI=$EC2_AMI_32BIT
+        ;;
+m1.large,m1.xlarge,m2.xlarge,m2.2xlarge,m2.4xlarge,c1.xlarge)
+        AMI=$EC2_AMI_64BIT
+        ;;
 *)
-	echo "error: unknown type: $TYPE" >&2
-	;;
+        echo "error: unknown type: $TYPE" >&2
+        ;;
 esac
 
 DATA=`mktemp -d /tmp/kuminami.XXXXXX`
